// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToContext(arg1) {
  return window['go']['main']['App']['ConnectToContext'](arg1);
}

export function DeletePreference(arg1) {
  return window['go']['main']['App']['DeletePreference'](arg1);
}

export function GetAllPreferences() {
  return window['go']['main']['App']['GetAllPreferences']();
}

export function GetContextAliases() {
  return window['go']['main']['App']['GetContextAliases']();
}

export function GetContexts() {
  return window['go']['main']['App']['GetContexts']();
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetNamespaces() {
  return window['go']['main']['App']['GetNamespaces']();
}

export function GetPodDetail(arg1, arg2) {
  return window['go']['main']['App']['GetPodDetail'](arg1, arg2);
}

export function GetPodEvents(arg1, arg2) {
  return window['go']['main']['App']['GetPodEvents'](arg1, arg2);
}

export function GetPods(arg1) {
  return window['go']['main']['App']['GetPods'](arg1);
}

export function GetPreference(arg1) {
  return window['go']['main']['App']['GetPreference'](arg1);
}

export function SetContextAlias(arg1, arg2) {
  return window['go']['main']['App']['SetContextAlias'](arg1, arg2);
}

export function SetPreference(arg1, arg2) {
  return window['go']['main']['App']['SetPreference'](arg1, arg2);
}
