// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToContext(arg1) {
  return window['go']['main']['App']['ConnectToContext'](arg1);
}

export function DeletePreference(arg1) {
  return window['go']['main']['App']['DeletePreference'](arg1);
}

export function GetAllPreferences() {
  return window['go']['main']['App']['GetAllPreferences']();
}

export function GetClusterHealth() {
  return window['go']['main']['App']['GetClusterHealth']();
}

export function GetContextAliases() {
  return window['go']['main']['App']['GetContextAliases']();
}

export function GetContexts() {
  return window['go']['main']['App']['GetContexts']();
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetDaemonSetDetail(arg1, arg2) {
  return window['go']['main']['App']['GetDaemonSetDetail'](arg1, arg2);
}

export function GetDaemonSetEvents(arg1, arg2) {
  return window['go']['main']['App']['GetDaemonSetEvents'](arg1, arg2);
}

export function GetDaemonSets(arg1) {
  return window['go']['main']['App']['GetDaemonSets'](arg1);
}

export function GetDeploymentDetail(arg1, arg2) {
  return window['go']['main']['App']['GetDeploymentDetail'](arg1, arg2);
}

export function GetDeploymentEvents(arg1, arg2) {
  return window['go']['main']['App']['GetDeploymentEvents'](arg1, arg2);
}

export function GetDeployments(arg1) {
  return window['go']['main']['App']['GetDeployments'](arg1);
}

export function GetNamespaces() {
  return window['go']['main']['App']['GetNamespaces']();
}

export function GetNodeDetail(arg1) {
  return window['go']['main']['App']['GetNodeDetail'](arg1);
}

export function GetNodeEvents(arg1) {
  return window['go']['main']['App']['GetNodeEvents'](arg1);
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetPodDetail(arg1, arg2) {
  return window['go']['main']['App']['GetPodDetail'](arg1, arg2);
}

export function GetPodEvents(arg1, arg2) {
  return window['go']['main']['App']['GetPodEvents'](arg1, arg2);
}

export function GetPods(arg1) {
  return window['go']['main']['App']['GetPods'](arg1);
}

export function GetPreference(arg1) {
  return window['go']['main']['App']['GetPreference'](arg1);
}

export function GetStatefulSetDetail(arg1, arg2) {
  return window['go']['main']['App']['GetStatefulSetDetail'](arg1, arg2);
}

export function GetStatefulSetEvents(arg1, arg2) {
  return window['go']['main']['App']['GetStatefulSetEvents'](arg1, arg2);
}

export function GetStatefulSets(arg1) {
  return window['go']['main']['App']['GetStatefulSets'](arg1);
}

export function SetContextAlias(arg1, arg2) {
  return window['go']['main']['App']['SetContextAlias'](arg1, arg2);
}

export function SetPreference(arg1, arg2) {
  return window['go']['main']['App']['SetPreference'](arg1, arg2);
}

export function StartHealthCheck() {
  return window['go']['main']['App']['StartHealthCheck']();
}

export function StopHealthCheck() {
  return window['go']['main']['App']['StopHealthCheck']();
}

export function UnwatchAll() {
  return window['go']['main']['App']['UnwatchAll']();
}

export function WatchPods(arg1) {
  return window['go']['main']['App']['WatchPods'](arg1);
}
