// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kube} from '../models';

export function ConnectToContext(arg1:string):Promise<void>;

export function DeletePreference(arg1:string):Promise<void>;

export function GetAllPreferences():Promise<Record<string, any>>;

export function GetContextAliases():Promise<Record<string, string>>;

export function GetContexts():Promise<Array<kube.Context>>;

export function GetCurrentContext():Promise<string>;

export function GetNamespaces():Promise<Array<string>>;

export function GetPodDetail(arg1:string,arg2:string):Promise<kube.PodDetail>;

export function GetPodEvents(arg1:string,arg2:string):Promise<Array<kube.EventInfo>>;

export function GetPods(arg1:string):Promise<Array<kube.PodInfo>>;

export function GetPreference(arg1:string):Promise<any>;

export function SetContextAlias(arg1:string,arg2:string):Promise<void>;

export function SetPreference(arg1:string,arg2:any):Promise<void>;
